mavproxy_cmdlong: attitude add angular rates & mask
ArduPilot/MAVProxy pull request #1002
Opened 2022-01-30 23:26 UTC by hendjoshsr71

This updates the attitude command so you send the typemask and angular velocities.

![image](https://user-images.githubusercontent.com/69225461/151722308-476b50a2-bd4d-4f07-8a08-87a644f2be3d.png)

2022-02-28 23:23 UTC, tridge requested changes

2022-02-28 23:23 UTC, tridge commented on MAVProxy/modules/mavproxy_cmdlong.py
> +            print("Usage: attitude mask q0 q1 q2 q3 roll_rate pitch_rate yaw_rate thrust (0~1)")
units, so roll_rate(deg/s)

2022-02-28 23:23 UTC, tridge commented on MAVProxy/modules/mavproxy_cmdlong.py
> -        '''attitude q0 q1 q2 q3 thrust'''
support the old 5 arg version

2022-02-28 23:24 UTC, tridge commented on MAVProxy/modules/mavproxy_cmdlong.py
> +            print("Usage: attitude mask q0 q1 q2 q3 roll_rate pitch_rate yaw_rate thrust (0~1)")
or 2nd line of usage saying rates are in deg/sec
and quaternion convention

2022-03-02 08:46 UTC, hendjoshsr71 commented on MAVProxy/modules/mavproxy_cmdlong.py
> -        '''attitude q0 q1 q2 q3 thrust'''
done

2022-03-15 00:04 UTC, tridge approved these changes

2022-03-15 03:01 UTC, merged