map: mp_elevation: take and pass cachedir through in ElevationModel init
ArduPilot/MAVProxy pull request #1088
Opened 2022-08-01 05:12 UTC by peterbarker

This allows a user to point to special places they may be storing their data

2022-08-01 20:43 UTC, tridge requested changes

2022-08-01 20:43 UTC, tridge commented on MAVProxy/modules/mavproxy_map/mp_elevation.py
> +    def __init__(self, database='SRTM3', cachedir=None, offline=0, debug=False):
please add the new parameter at the end so existing users that do EvelationModel("SRTM", True) still work

2022-08-01 22:57 UTC, tridge commented on MAVProxy/modules/mavproxy_map/mp_elevation.py
> +    def __init__(self, offline=0, database='SRTM3', cachedir=None, debug=False):
still changes order

2022-08-01 23:08 UTC, tridge approved these changes

2022-08-01 23:08 UTC, merged

2022-10-11 07:52 UTC, peterbarker commented
On Mon, 1 Aug 2022, Andrew Tridgell wrote:

> -    def __init__(self, database='SRTM3', offline=0, debug=False):
> +    def __init__(self, database='SRTM3', cachedir=None, offline=0, debug=False):
> 
> please add the new parameter at the end so existing users that do EvelationModel("SRTM", True) still work

That wouldn't work - "database" is the first positional argument there.

I've moved "offline" to be the first positional argument, which I think is 
what you wanted.