misseditor: Better mission command dropdown
ArduPilot/MAVProxy pull request #1233
Opened 2023-08-29 06:18 UTC by stephendade

Fix for #1162.

Modifies the mission editor's "Command" dropdown to use a custom control (ListCtrl), which has a better layout and visible scrollbars.

Tested on WSL and Ubuntu 22:

![Screenshot 2023-08-29 161219](https://github.com/ArduPilot/MAVProxy/assets/1731976/0f1549fa-cfa4-49e0-8fde-f5d2e1ea7b5e)

@rmackay9 - I'd be interested if this works better for you.

2023-08-29 07:55 UTC, rmackay9 commented
Thank you so much!

2023-09-12 07:55 UTC, stephendade commented
@rmackay9, would you be able to give this a test-drive? Mostly just to see if the GUI changes work for you.

I'll get @tridge or @peterbarker to do the actual code review.

2023-09-12 11:49 UTC, rmackay9 commented
Hi @stephendade,

Yes, I'll give this a test.  I'm not very confident about building MAVproxy from source but I'll try.

2023-09-13 00:41 UTC, rmackay9 commented
Hi @stephendade,

I gave this a test and it is certainly better than master because I can actually get to the commands I'd like to add.

It is a bit weird though, sometimes when I click on an existing command and try to change it, the drop-down appears behind the wp editor.
![image](https://github.com/ArduPilot/MAVProxy/assets/1498098/04708e67-6f0f-4ebd-84fa-e578ed012172)

2023-09-15 05:45 UTC, stephendade commented
> It is a bit weird though, sometimes when I click on an existing command and try to change it, the drop-down appears behind the wp editor. It also appeared to me that at least once the list of commands was not sorted alphabetically although I'm now having troubles reproducing this.

I've managed to replicate this. It's a x11 vs Wayland issue again. @MichelleRos had similar issues and fixed it via putting ``GDK_BACKEND="x11"`` in ``~\.bashrc`` and restarting.

I've confirmed if you do the same, it should fix the window focus issue.

2023-09-15 06:11 UTC, rmackay9 approved these changes
@stephendade,

Yes, that's fixed it for me as well.  I had to add "**export** GDK_BACKEND="x11"".

2023-09-15 23:32 UTC, peterbarker requested changes
@stephendade I can reliably produce this assertion:
```
wx._core.wxAssertionError: C++ assertion "firstHandler != this" failed at ../src/common/wincmn.cpp(1461) in PopEventHandler(): cannot pop the wxWindow itself

The above exception was the direct cause of the following exception:

SystemError: _PyEval_EvalFrameDefault returned a result with an exception set

```

... by selecting a type which ArduPilot doesn't undertstand, writing waypoints then reading waypoints.

2023-09-17 11:36 UTC, stephendade commented
> @stephendade I can reliably produce this assertion:
> 
> ```
> wx._core.wxAssertionError: C++ assertion "firstHandler != this" failed at ../src/common/wincmn.cpp(1461) in PopEventHandler(): cannot pop the wxWindow itself
> 
> The above exception was the direct cause of the following exception:
> 
> SystemError: _PyEval_EvalFrameDefault returned a result with an exception set
> ```
> 
> ... by selecting a type which ArduPilot doesn't undertstand, writing waypoints then reading waypoints.

Now fixed. It was a reference counting issue (see https://github.com/wxWidgets/Phoenix/issues/627)

2023-09-17 23:32 UTC, merged

2023-09-17 23:32 UTC, peterbarker commented
Merged, thanks!