Add new modules to support uploading Fence and Rally with Mission Item Protocol
ArduPilot/MAVProxy pull request #676
Opened 2019-08-29 04:27 UTC by peterbarker

.... also changes to mavproxy_map to allow manipulation of same.

There are some bits that need to be done before merging - see related ArduPilot PR for details.

Most notable is the option to force fallback to the older protocols in case something goes wrong with the new.

2022-05-27 07:49 UTC, tridge commented
@peterbarker ping?

2023-07-22 03:27 UTC, tridge commented
@peterbarker it seems to be missing some changes in mavwp: ```
Traceback (most recent call last):
  File "/home/tridge/.local/bin/mavproxy.py", line 4, in <module>
    __import__('pkg_resources').run_script('MAVProxy==1.8.65', 'mavproxy.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/home/tridge/.local/lib/python3.10/site-packages/MAVProxy-1.8.65-py3.10.egg/EGG-INFO/scripts/mavproxy.py", line 1448, in <module>
  File "/home/tridge/.local/lib/python3.10/site-packages/MAVProxy-1.8.65-py3.10.egg/EGG-INFO/scripts/mavproxy.py", line 530, in load_module
  File "/home/tridge/.local/lib/python3.10/site-packages/MAVProxy-1.8.65-py3.10.egg/MAVProxy/modules/mavproxy_rally.py", line 143, in init
  File "/home/tridge/.local/lib/python3.10/site-packages/MAVProxy-1.8.65-py3.10.egg/MAVProxy/modules/mavproxy_rally.py", line 21, in __init__
AttributeError: module 'pymavlink.mavwp' has no attribute 'MissionItemProtocol_Rally'
```
maybe we should just not load rally module if this fails?

2023-07-22 21:58 UTC, tridge requested changes
the FEN icon in console doesn't seem to be updating correctly? Shows as grey with a fence enabled and in breach

2023-07-22 21:58 UTC, tridge commented on MAVProxy/modules/lib/mission_item_protocol.py
> +        print("Processing %s request: (%s)" % (self.itemtype(), str(m)))
this debug is very annoying

2023-07-22 21:58 UTC, tridge commented on MAVProxy/modules/lib/mission_item_protocol.py
> +        print("args: %s" % str(args))
remove debug

2023-07-22 21:58 UTC, tridge commented on MAVProxy/modules/lib/mission_item_protocol.py
> +        print(self.csv_line(headers))
needed?

2023-07-22 21:58 UTC, tridge commented on MAVProxy/modules/lib/mission_item_protocol.py
> +            print(self.csv_line(out_list))
more debug

2023-07-22 21:58 UTC, tridge commented on MAVProxy/modules/lib/mission_item_protocol.py
> +        print("Fetching mission with ftp")
not needed

2023-07-23 02:59 UTC, peterbarker reviewed
Fixed

2023-07-23 22:56 UTC, peterbarker commented
> the FEN icon in console doesn't seem to be updating correctly? Shows as grey with a fence enabled and in breach

This turned out to be because the action was report-only.

2023-07-29 23:48 UTC, tridge approved these changes

2023-07-29 23:48 UTC, merged