Precland setter
ArduPilot/MAVProxy pull request #889
Opened 2021-05-18 13:51 UTC by khancyr

Add an option on right click to set SITL precland beacon position

2021-06-08 22:21 UTC, tridge requested changes

2021-06-08 22:21 UTC, tridge commented on MAVProxy/modules/mavproxy_map/__init__.py
> +        self.add_menu(MPMenuItem('Set Precland', 'Set Precland', '# map setprecland '))
we shouldn't add the menu item if not in SITL, so we don't confuse users

2021-07-02 03:39 UTC, peterbarker commented
Nudge @khancyr

2021-07-02 07:01 UTC, khancyr commented
@peterbarker done !

2021-07-06 21:35 UTC, closed without merging